### ISSUE TITLE
the HSA runtime has install,but ...

### ISSUE THREAD

**Issue by x-xiaojian** [NUCAR-DEV/Hetero-Mark#51]
/opt/rocm/hsa
/usr/bin/snackhsail.sh
HSA_RUNTIME-NOTFOUND
snackhsail.sh or hsa runtime not found, skipping HSA benchmarks

**Comment by syifan** [comment]
Can you try adding the following lines to your .bashrc file?

``` bash
export HSA_RUNTIME_PATH=/opt/rocm/hsa
export PATH=$PATH:/opt/rocm/bin
export PATH=$PATH:/opt/rocm/cloc/bin
export LD_LIBRARY_PATH=$HSA_RUNTIME_PATH/lib
```

**Comment by x-xiaojian** [comment]
thank you!I have solved it.
1.  HSA_RUNTIME-NOTFOUND
HAS.cmake
find_library(HSA_RUNTIME 
  NAMES libhsa-runtime64.so.1
  PATHS ${HSA_RUNTIME_PATH}/lib
  NO_DEFAULT_PATH)：
2.  ERROR:  Missing HSAILasm
find_file(have_snack NAMES snack.sh DOC "snack.sh file")
set(SNACK "snack.sh")
3.  /bin/sh: 1: hcc-config: not found
sudo ln -sf /opt/rocm/hcc/bin/hcc-config /usr/bin/hcc-config
4.  /bin/sh: 1: hcc: not found
sudo ln -sf /opt/rocm/hcc/bin/hcc /usr/bin/hcc

but there are some  problems about opencl ！！！
Scanning dependencies of target benchmark
[  1%] Building CXX object src/common/benchmark/CMakeFiles/benchmark.dir/benchmark_runner.cc.o
In file included from /home/xb103/Downloads/Hetero-Mark-Develop/src/common/benchmark/benchmark_runner.cc:41:
In file included from /home/xb103/Downloads/Hetero-Mark-Develop/src/common/benchmark/benchmark_runner.h:44:
In file included from /home/xb103/Downloads/Hetero-Mark-Develop/src/common/benchmark/benchmark.h:44:
/home/xb103/Downloads/Hetero-Mark-Develop/src/common/time_measurement/time_measurement.h:44:10: fatal error: 
      'iostream' file not found
#include <iostream>
         ^
1 error generated.
src/common/benchmark/CMakeFiles/benchmark.dir/build.make:54: recipe for target 'src/common/benchmark/CMakeFiles/benchmark.dir/benchmark_runner.cc.o' failed
make[2]: **\* [src/common/benchmark/CMakeFiles/benchmark.dir/benchmark_runner.cc.o] Error 1
CMakeFiles/Makefile2:172: recipe for target 'src/common/benchmark/CMakeFiles/benchmark.dir/all' failed
make[1]: **\* [src/common/benchmark/CMakeFiles/benchmark.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by syifan** [comment]
I cannot recreate the problem, and the problem seems weird. Can you provide some more detail about your platform? Which version of Linux you are running, and what is the version of g++? BTW, the error is not in OpenCL, if you have HSA enabled on your machine, OpenCL compilation is disabled by Hetero-Mark.

**Comment by x-xiaojian** [comment]
thank you! This problem is to another machine.Other opencl program can be run correctly.Theversion of Linux I am running is Ubuntu 15.04,and g++ is 4.9.2
