### ISSUE TITLE
My CPU is A10-7870K,there is a error when runing your benchmark.

### ISSUE THREAD

**Issue by x-xiaojian** [NUCAR-DEV/Hetero-Mark#52]
ERROR: This processor assumes device is fiji
       The device object code was compiled for a kaveri.
       Recompile or run this binary with a kaveri

**Comment by syifan** [comment]
Do you mind providing more detail about your error? Which version of ROCm is installed? Which application were you running when you see this error?

**Comment by x-xiaojian** [comment]
The rocm is rocm1.4.0, and all of the hsa application would  produce errors,such as aes,fir.

**Comment by syifan** [comment]
Ok, I have not updated to rocm 1.4 yet. But I can try to recreate your problem next week. Thank you very much.

**Comment by syifan** [comment]
Newer version of ROCm stopped the support for Kaveri APUs. The newly updated code support running the benchmarks on discrete GPUs with ROCm 1.6.
