### ISSUE TITLE
build problems for HC benchmarks

### ISSUE THREAD

**Issue by apanqasem** [NUCAR-DEV/Hetero-Mark#56]
I am having problems building the HC benchmarks (be, bs, ga and ep). They build fine on AMD7850 and AMD8500.  However, when I attempt to execute the program, I get the following:

`### HCC STATUS_CHECK Error: HSA_STATUS_ERROR_INCOMPATIBLE_ARGUMENTS (0x100d) at file: /hcc-rocm-1.4.x/hcc/lib/hsa/mcwamp_hsa.cpp line:2511`

This usually means that the code was generated for a different target. Is there a place where the target architecture flag is being set?

I am using 

ROCM 1.4.0 
HCC based on clang 3.5.0 

I was able to build and execute the HSA versions on these system without any problems

**Comment by syifan** [comment]
Hi @apanqasem 

We are also experiencing some problem after upgrading to ROCm 1.4. The code needs to be updated to work with ROCm 1.4 and discrete GPUs. 

For the compiler code target, by the time we develop the benchmark-suite, HCC compiler does not need to set that yet. But now we need to set the target. We are also upgrading the cmake files to meet the new settings. 

Thanks,
Yifan

**Comment by apanqasem** [comment]
Yifan, 

Thanks for your reply. I did manage to build all nine benchmarks by explicitly setting the targets in the makefile. 

On the APU node (gfx801), we are getting segfautls from bs and ep. Is this known/expected bahavior?

- Apan



[error_log_bs.txt](https://github.com/NUCAR-DEV/Hetero-Mark/files/852554/error_log_bs.txt)
[error_log_ep.txt](https://github.com/NUCAR-DEV/Hetero-Mark/files/852555/error_log_ep.txt)

**Comment by syifan** [comment]
Hi @apanqasem 

That is something related to the problem that I mentioned that Hetero-Mark cannot support ROCm 1.4. We are also experiencing that error and we are trying to solve them. 

I have a question for you. Were you able to run the [official examples ](https://github.com/RadeonOpenCompute/HCC-Example-Application) on your platform? I am experiencing some segfault on our Carrizo platform. I filed an [issue](https://github.com/RadeonOpenCompute/ROCm/issues/83) on the ROCm github repo, but got no reply yet.

**Comment by apanqasem** [comment]
Yifan, 

Yes, they work fine for me on Carrizo. I did have to make the requisite changes to the make files. 

Do you have the latest hcc on your system. I am using 0.10.16501

- Apan
