### ISSUE TITLE
hsa implementations

### ISSUE THREAD

**Issue by apanqasem** [NUCAR-DEV/Hetero-Mark#62]
Earlier versions contained HSA implementations, which appear to have been removed from the repo. Are there any plans for reinstating them?

**Comment by syifan** [comment]
No. CLOC and SNACK seems are not being actively maintained by AMD. So we do not have a good toolchain to support native HSA. HIP, OpenCL, and CUDA will be our focus for now.

**Comment by apanqasem** [comment]
Thanks for the info. I am actually a visiting researcher at AMD. I have been working with the HSA implementations in Hetero-Mark. I have the benchmarks working on APU nodes with ROCm 1.6. I had to tweak both CLOC and SNACK to get the codes to build and run. I am working on discrete GPU nodes now. I was just wondering if there were major changes to the benchmark codes which I cloned back in March.

**Comment by syifan** [comment]
So when we upgrade to ROCm 1.6, the SNACK version of the benchmarks does not run. I noticed there was an error in the snack generated code. As I recently ran 'apt-get upgrade', there were some new errors in CLOC. As OpenCL is natively supported by ROCm, we think there is no need to continue the support of the SNACK version. If you have cloned the code in March, there is no major change in the code. The updates just add new benchmarks and make existing code more robust.

**Comment by apanqasem** [comment]
Yes, I agree, it does not make sense to continue support for CLOC/SNACK version. 

I am working on stuff where I need the low-level memory management control provided by HSA.  That's why I was interested in that version of the benchmarks. But I can by-pass SNACK and port the codes to native HSA.  Thanks for the info.
