### ISSUE TITLE
application design patterns

### ISSUE THREAD

**Issue by apanqasem** [NUCAR-DEV/Hetero-Mark#63]
Is there a paper that documents the design patterns (e.g., C2G, C2GI) for some of the newer benchmarks (e.g., ep)?

**Comment by syifan** [comment]
@apanqasem 

Here are two papers we published recently. 

https://www.researchgate.net/publication/309206460_Hetero-Mark_A_Benchmark_Suite_for_CPU-GPU_Collaborative_Computing
https://www.researchgate.net/publication/323745962_Evaluating_Performance_Tradeoffs_on_the_Radeon_Open_Compute_Platform

Note that the second paper is not presented at the conference yet. There are some benchmarks and features mentioned in the second paper but are not included in the current Github repo. We are still organizing it and we will publish the code soon.

**Comment by apanqasem** [comment]
got it, thanks.
