### ISSUE TITLE
Broken link to paper on README

### ISSUE THREAD

**Issue by agostini01** [NUCAR-DEV/Hetero-Mark#66]
the link for the paper bellow is broken

> Yifan Sun, Saoni Mukherjee, Trinayan Baruah, Shi Dong, Julian Gutierrez, Prannoy Mohan and David Kaeli, "Evaluating Performance Tradeoffs on the Radeon Open Compute Platform" 2018 IEEE International Symposium on Performance Analysis of Systems and Software (ISPASS), Belfast, 2018.

**Comment by syifan** [comment]
Thanks for the issue. It is fixed in b6e6f42
