### ISSUE TITLE
support for CUDA 10.0

### ISSUE THREAD

**Issue by apanqasem** [NUCAR-DEV/Hetero-Mark#73]
Is there a patch for CUDA 10.0? 

I installed Hetero-Mark on a POWER9 system with Ubuntu 18.04 and CUDA 10.0. The build went smoothly. No warnings from cmake or make. But verification test fails for all applications. In particular, it appears that the device data structures are not being copied back to host. They contain the original values prior to kernel launch. 

Is this a known issue? 

My system works fine other benchmarks suites I am running (e.g., Parboil, Rodinia).

**Comment by syifan** [comment]
We have not tried to use CUDA 10.0 yet. Do the workloads run on an earlier version of CUDA. We have also never tried to run the benchmarks on a Power9 machine.

**Comment by apanqasem** [comment]
Thanks. The workloads run fine with CUDA 9.1 on that same Power9 machine. 

I will let you know if I figure it out.

**Comment by syifan** [comment]
Let me know if you find any problem with the code. I am happy to fix it.
