### ISSUE TITLE
cmake question

### ISSUE THREAD

**Issue by zjin-lcf** [NUCAR-DEV/Hetero-Mark#75]
Do you mind updating the scripts for the error:

  Unknown CMake command "cuda_add_executable".

Thanks

**Comment by syifan** [comment]
@zjin-lcf Do you mind giving us some help on solving it? This problem may be mentioned here https://stackoverflow.com/questions/46568779/cmake-error-using-cuda-add-executable-command.

**Comment by zjin-lcf** [comment]
cmake 19 works for me, so I will close the issue.
